# Generated by Django 4.0.5 on 2022-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electricals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('itemprice', models.CharField(max_length=20)),
                ('itemquantity', models.CharField(max_length=20)),
                ('totalamount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('itemprice', models.CharField(max_length=20)),
                ('itemquantity', models.CharField(max_length=100)),
                ('totalamount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='welding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('itemprice', models.CharField(max_length=20)),
                ('itemquantity', models.CharField(max_length=100)),
                ('totalamount', models.CharField(max_length=20)),
            ],
        ),
    ]
